config/routes.rb
Scanner::Application.routes.draw do
  resources :users

  resources :products

  resources :sessions
  match 'logout', to: 'sessions#destroy', as: :logout
  match 'login', to: 'sessions#new', as: :login

  resources :customers do
    member do
      get :products
    end
  end

  namespace :api do
    namespace :v1 do
      resources :customers
      resources :checkin
    end
  end

  root :to => 'customers#index'

end

app/helpers/layout_helper.rb
module LayoutHelper

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def submenu(&block)
    content_for(:submenu) { capture(&block) }
    @show_submenu = true
  end

  def show_submenu?
    @show_submenu
  end

  # Wraps a standard link_to call with an li tag with a possible class of active.
  #
  # Without any additional arguments the current url must match the linked url to be active.
  # e.g. active_link_to('Users', users_path) is only active on users_path.
  #
  # To make multiple pages active pass in an array of urls to the active_paths option.
  # e.g. active_link_to('Users', users_path, active_paths: [users_path, new_user_path, @user, [:edit, @user]])
  #   is active on users_path, new_user_path, user_path(@user) and edit_user_path(@user)
  # or an array of controllers,
  # e.g. active_link_to('Users', users_path, active_controllers: [:leads, :documents])
  def active_link_to(*args, &block)
    if block_given?
      active_link_to(capture(&block), args.first || {}, args.second)
    else
      active = false
      html_options = args.third || {}
      active_paths = html_options.delete(:active_paths)
      active_controllers = html_options.delete(:active_controllers)
      if active_paths.nil? && active_controllers.nil?
        active = true if request.fullpath == args.second
      else
        active_paths.to_a.each do |url_object|
          next if url_object.nil?
          next if url_object.respond_to?(:second) && !url_object.try(:second).try(:persisted?)
          active = request.path == url_for(url_object)
          break if active
        end
        active_controllers.to_a.each do |controller|
          active = params[:controller] == controller.to_s
          break if active
        end
      end
      content_tag :li, active ? { class: 'active' } : nil do
        link_to(*args)
      end
    end
  end

end

app/views/layouts/_flash_hash.html.haml
- flash.each do |key, message|
  -# Bootstrap has warning, error, success and info; Rails has alert and notice
  - key = :error if key == :alert
  - key = :success if key == :notice
  %div{:class => "alert alert-#{key}"}
    %button.close{:data => {:dismiss => "alert"}} &times;
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title)
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Check-In Kiosk Admin", root_path, class: 'brand'
          %ul.nav
            %li= active_link_to "Customers", customers_path, active_controllers: [:customers]
            %li= active_link_to "Products", products_path, active_controllers: [:products]
            %li= active_link_to "Users", users_path, active_controllers: [:users]
          %ul.nav.pull-right
            - if logged_in?
              %li.dropdown
                = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Edit Profile', [:edit, current_user]
                  %li.divider
                  %li
                    = link_to 'Log Out', logout_path
    .container
      %h1.clearfix
        .pull-left= yield(:title)
        - if show_submenu?
          #submenu.pull-right
            = yield :submenu
      = yield

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %title= yield(:title)
    %meta{name: "viewport", content: "width=device-width, scale=1.0"}
    = stylesheet_link_tag "mobile", :media => "all"
    = javascript_include_tag "mobile"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/sessions.html.haml
!!!
%html
  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = csrf_meta_tag
  %body
    .container
      = yield

    = javascript_include_tag :application